spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-atguigu-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-atguigu-test