spring:
  profiles: dev
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
       defaultZone: http://eureka-dev.com:7001/eureka/
       
---
spring:
  profiles:
    active:
      - test
---
server:
  port: 8203
spring:
  profiles: test
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
       defaultZone: http://eureka-test.com:7001/eureka/
  